[Interface]
# Peer 2 - Rete B (10.0.2.0/24)
PrivateKey = 2M3P9L1qT6Y8+VhKT3TUJ8F8DgQ9xPWL6T6k2FKBgRx=
Address = 10.0.2.1/24
ListenPort = 51821

[Peer]
# WPEX Server
PublicKey = xPWL6T6k2FKBgRxF5a8gzSHWaUuT+VhKT3TUJ8F8DgQ=
Endpoint = localhost:40000
AllowedIPs = 10.0.1.0/24
PersistentKeepalive = 25