[Interface]
# Peer 1 - Rete A (10.0.1.0/24)
PrivateKey = KBY8b5pU8YrFjIp3/kT2BMpC2LdGSXr5yd5+a4XYd38=
Address = 10.0.1.1/24
ListenPort = 51820

[Peer]
# WPEX Server
PublicKey = xPWL6T6k2FKBgRxF5a8gzSHWaUuT+VhKT3TUJ8F8DgQ=
Endpoint = localhost:40000
AllowedIPs = 10.0.2.0/24
PersistentKeepalive = 25